### ISSUE TITLE
Add style components and spice up front-end

### ISSUE THREAD

**Issue by thealphacubicle** [thealphacubicle/MBTA-Dashboard#3]
**Goal**: Revise Dash components and layout work

**To-Do**:
- [ ] Finish column description callback function using column metadata (the `print_column_info` function)
- [ ] Change the navbar color for the brand name from black to white so we can see the name of it
- [ ] Replace the graph inside the `update_ride_type_bar_chart` callback function to have the KDE plot instead
- [ ] Add functionality for graphing in the `viz_statistics_of_column` callback function. A callback error is thrown when you select `started_at` and `ended_at` as the columns you want to explore.
- [ ] Add an about section description to the project
- [ ] Clean up code + add documentation

**Comment by thealphacubicle** [comment]
Current layout of dashboard:


![Image](https://github.com/thealphacubicle/BlueBike-Dashboard/assets/74083272/404e57d3-0147-43b1-ab1a-7d741e3921f0)
![Image](https://github.com/thealphacubicle/BlueBike-Dashboard/assets/74083272/0198f832-b288-439c-adab-f85ae1bdda56)
